apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: ink-homelab
    credentials-file: /etc/cred.json
    ingress:
      - hostname: "*.overeazy.io"
        service: http://traefik.traefik.svc:80
      - hostname: "dashboard.overeazy.io"
        service: http://homepage.homepage.svc:80
    warp-routing:
      enabled: false
