apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  config.json: |
    {
      "services": [
        {
          "group": "Collaboration",
          "items": [
            {
              "name": "Rocket.Chat",
              "href": "https://chat.{{ .Env.DOMAIN_BASE }}",
              "icon": "rocketchat.png"
            },
            {
              "name": "WorkAdventure",
              "href": "https://workadventure.{{ .Env.DOMAIN_BASE }}",
              "icon": "workadventure.png"
            },
            {
              "name": "Jitsi",
              "href": "https://jitsi.{{ .Env.DOMAIN_BASE }}",
              "icon": "jitsi.png"
            }
          ]
        },
        {
          "group": "AI",
          "items": [
            {
              "name": "Open WebUI",
              "href": "https://webui.{{ .Env.DOMAIN_BASE }}",
              "icon": "ai.png"
            },
            {
              "name": "Langflow",
              "href": "https://langflow.{{ .Env.DOMAIN_BASE }}",
              "icon": "langflow.png"
            },
            {
              "name": "SearXNG",
              "href": "https://searxng.{{ .Env.DOMAIN_BASE }}",
              "icon": "search.png"
            }
          ]
        },
        {
          "group": "Productivity",
          "items": [
            {
              "name": "AppFlowy",
              "href": "https://appflowy.{{ .Env.DOMAIN_BASE }}",
              "icon": "appflowy.png"
            },
            {
              "name": "LinkWarden",
              "href": "https://linkwarden.{{ .Env.DOMAIN_BASE }}",
              "icon": "linkwarden.png"
            },
            {
              "name": "Homebox",
              "href": "https://homebox.{{ .Env.DOMAIN_BASE }}",
              "icon": "homebox.png"
            }
          ]
        }
      ],
      "layout": "columns",
      "theme": "dark",
      "showSearch": true,
      "background": "simple",
      "color": "slate"
    }
