apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocketchat-ingress
  namespace: rocketchat
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "rocketchat-forward-auth@kubernetescrd"
spec:
  rules:
    - host: chat.${DOMAIN_BASE}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rocketchat
                port:
                  number: 80